services:
    obsidian-headless:
        build:
            context: .
            args:
                UID: ${UID:-1000}
                GID: ${GID:-1000}
        image: obsidian-headless
        volumes:
            - ${CONFIG_PATH}:/home/obsidian/.config/obsidian-headless
            - ${VAULT_PATH}:/vault
